# Generated by Django 6.0.7 on 2026-07-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('date', models.DateField(db_index=True, help_text='Target metric aggregation date.', unique=True)),
                ('total_bookings', models.PositiveIntegerField(default=0, help_text='Count of confirmed bookings on this day.')),
                ('total_tickets_sold', models.PositiveIntegerField(default=0, help_text='Sum of seat tickets sold.')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total ticket revenue in INR.', max_digits=12)),
                ('average_occupancy_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage average seat occupancy across all screens.', max_digits=5)),
            ],
            options={
                'verbose_name': 'Daily Analytics Summary',
                'verbose_name_plural': 'Daily Analytics Summaries',
                'ordering': ['-date'],
            },
        ),
    ]
