# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('start_time', models.DateTimeField(db_index=True, help_text='Exact timestamp when the show begins.', verbose_name='Screening Start Time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Estimated timestamp when show ends (including trailers).', null=True, verbose_name='Screening End Time')),
                ('base_price', models.DecimalField(db_index=True, decimal_places=2, help_text='Standard regular seat ticket price in INR.', max_digits=7, verbose_name='Base Ticket Price')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming / Scheduled'), ('OPEN', 'Booking Open'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='OPEN', help_text='Booking status lifecycle stage.', max_length=20)),
                ('available_seats', models.PositiveIntegerField(default=100, help_text='Current real-time tally of unbooked seats.')),
                ('movie', models.ForeignKey(help_text='Movie scheduled for screening.', on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('screen', models.ForeignKey(help_text='Auditorium screen hosting the show.', on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='theaters.screen')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time'], name='shows_show_start_t_33f338_idx'), models.Index(fields=['movie', 'start_time'], name='shows_show_movie_i_3b276b_idx'), models.Index(fields=['screen', 'start_time'], name='shows_show_screen__59760c_idx'), models.Index(fields=['base_price'], name='shows_show_base_pr_f553c0_idx'), models.Index(fields=['status'], name='shows_show_status_e643ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('screen', 'start_time'), name='unique_screen_show_start_time')],
            },
        ),
    ]
