# Generated by Django 5.1.15 on 2026-08-08 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous visitor session key.', max_length=40, null=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Temporarily Reserved'), ('EXPIRED', 'Reservation Expired'), ('CONFIRMED', 'Confirmed into Booking')], db_index=True, default='RESERVED', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Exact timestamp (2 minutes from creation) when reservation expires.')),
                ('seat', models.ForeignKey(help_text='Specific seat reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='theaters.seat')),
                ('show', models.ForeignKey(help_text='Showtime for which the seat is reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='shows.show')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user holding the reservation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seat Reservation',
                'verbose_name_plural': 'Seat Reservations',
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['show', 'seat', 'status'], name='shows_seatr_show_id_b865f3_idx'), models.Index(fields=['expires_at', 'status'], name='shows_seatr_expires_ed702a_idx')],
            },
        ),
    ]
