# Generated by Django 5.1.15 on 2026-08-08 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_and_more'),
        ('shows', '0002_seatreservation'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Temporarily Reserved'), ('BOOKED', 'Booked')], db_index=True, default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Calculated price for this specific seat on this show.', max_digits=7)),
            ],
            options={
                'verbose_name': 'Show Seat',
                'verbose_name_plural': 'Show Seats',
                'ordering': ['seat__row', 'seat__number'],
            },
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='reservation_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique UUID grouping token for multi-seat 2-minute hold.', max_length=64),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated total price for reserved seats.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active 2-Min Hold'), ('RESERVED', 'Temporarily Reserved'), ('EXPIRED', 'Reservation Expired'), ('CONVERTED', 'Converted to Booking'), ('CONFIRMED', 'Confirmed into Booking'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['reservation_token'], name='shows_seatr_reserva_29d6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['user', 'status'], name='shows_seatr_user_id_d2b028_idx'),
        ),
        migrations.AddField(
            model_name='showseat',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Confirmed booking for this seat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_seats', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='showseat',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Active 2-minute reservation holding this seat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_seats', to='shows.seatreservation'),
        ),
        migrations.AddField(
            model_name='showseat',
            name='seat',
            field=models.ForeignKey(help_text='Physical seat location.', on_delete=django.db.models.deletion.CASCADE, related_name='show_assignments', to='theaters.seat'),
        ),
        migrations.AddField(
            model_name='showseat',
            name='show',
            field=models.ForeignKey(help_text='Scheduled showtime.', on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='shows.show'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'status'], name='shows_shows_show_id_154d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'seat'], name='shows_shows_show_id_08c4ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='showseat',
            constraint=models.UniqueConstraint(fields=('show', 'seat'), name='unique_show_seat'),
        ),
    ]
