# Generated by Django 5.1.15 on 2026-08-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('shows', '0003_showseat_seatreservation_reservation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Screening audio/dub language for this show.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='movies.language'),
        ),
    ]
