# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Primary email address used for login and electronic ticket delivery.', max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, help_text='User mobile number for SMS notifications and booking confirmations.', max_length=15, null=True, verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('THEATER_ADMIN', 'Theater Manager'), ('SITE_ADMIN', 'System Administrator')], db_index=True, default='CUSTOMER', help_text='Role determining access permissions across customer portal and management dashboards.', max_length=20, verbose_name='User Role')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', help_text='User profile picture stored in media directory.', null=True, upload_to='avatars/', verbose_name='Profile Avatar')),
                ('city_preference', models.CharField(blank=True, default='Hyderabad', help_text='Default city used to filter showtimes and theater listings.', max_length=100, verbose_name='Preferred City')),
                ('bio', models.TextField(blank=True, help_text='Brief profile bio or user status message.', max_length=500, verbose_name='User Bio')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was registered.', verbose_name='Account Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when user details were last updated.', verbose_name='Account Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
