# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Name of the city (e.g. Mumbai, Hyderabad, Bengaluru).', max_length=100, unique=True, verbose_name='City Name')),
                ('state', models.CharField(blank=True, help_text='State or province location.', max_length=100, verbose_name='State')),
                ('slug', models.SlugField(blank=True, help_text='URL slug generated from city name.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Commercial name of theater (e.g., PVR Forum Mall, INOX GVK One).', max_length=150, verbose_name='Theater Name')),
                ('slug', models.SlugField(blank=True, help_text='URL slug for theater page.', max_length=180)),
                ('address', models.TextField(help_text='Full street address and landmark details.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude coordinate for map integration.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude coordinate for map integration.', max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Operational status flag.')),
                ('city', models.ForeignKey(help_text='City where theater is located.', on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='theaters.city')),
            ],
            options={
                'verbose_name': 'Theater',
                'verbose_name_plural': 'Theaters',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Auditorium identifier (e.g. Screen 1, Audi 3).', max_length=50, verbose_name='Screen Name')),
                ('screen_type', models.CharField(choices=[('2D', 'Standard 2D'), ('3D', 'RealD 3D'), ('IMAX_3D', 'IMAX 3D'), ('4DX', '4DX Motion & Effects'), ('DOLBY_ATMOS', 'Dolby Atmos Cinema')], default='2D', help_text='Projection and sound format installed on screen.', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=100, help_text='Total seating capacity of screen.')),
                ('theater', models.ForeignKey(help_text='Parent theater hosting this screen.', on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'ordering': ['theater', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('row', models.CharField(help_text='Seating row code (e.g. A, B, C... M).', max_length=5, verbose_name='Row Letter')),
                ('number', models.PositiveIntegerField(help_text='Seat sequence number along the row (e.g. 1, 2, 12).', verbose_name='Seat Number')),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular Tier'), ('PREMIUM', 'Premium Tier'), ('VIP', 'VIP Luxury Tier'), ('RECLINER', 'Recliner Bed Tier')], default='REGULAR', help_text='Pricing tier and comfort classification.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Operational state (e.g., set to False if under repair).')),
                ('screen', models.ForeignKey(help_text='Auditorium screen hosting this seat.', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.screen')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['row', 'number'],
                'indexes': [models.Index(fields=['screen', 'seat_type'], name='theaters_se_screen__7e4688_idx')],
                'constraints': [models.UniqueConstraint(fields=('screen', 'row', 'number'), name='unique_screen_seat')],
            },
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['name'], name='theaters_th_name_1fa4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city', 'is_active'], name='theaters_th_city_id_014a38_idx'),
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('theater', 'name'), name='unique_theater_screen_name'),
        ),
    ]
