# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, help_text='Unique TMDb person identifier.', null=True, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Full legal or stage name of actor/crew.', max_length=150, verbose_name='Cast Member Name')),
                ('character_name', models.CharField(blank=True, help_text='Role played in movie (e.g. Tony Stark).', max_length=150, verbose_name='Character Name')),
                ('profile_image_url', models.URLField(blank=True, help_text='TMDb profile image thumbnail URL.', max_length=500)),
            ],
            options={
                'verbose_name': 'Cast Member',
                'verbose_name_plural': 'Cast Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the movie genre category.', max_length=50, unique=True, verbose_name='Genre Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug generated from genre name.', max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the language.', max_length=50, unique=True, verbose_name='Language Name')),
                ('code', models.CharField(help_text='ISO language code (e.g. en, hi, te, ta).', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, help_text='Unique TMDb movie ID for automated synchronization.', null=True, unique=True)),
                ('title', models.CharField(db_index=True, help_text='Official release title of the movie.', max_length=200, verbose_name='Movie Title')),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL identifier.', max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Promotional tagline phrase.', max_length=300)),
                ('description', models.TextField(help_text='Full narrative plot overview.', verbose_name='Synopsis')),
                ('poster', models.ImageField(blank=True, help_text='Locally uploaded high-resolution poster image.', null=True, upload_to='posters/')),
                ('poster_url', models.URLField(blank=True, help_text='Official remote TMDb poster CDN URL.', max_length=500)),
                ('backdrop_url', models.URLField(blank=True, help_text='Official remote TMDb banner/backdrop CDN URL.', max_length=500)),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube embed link for official trailer video.', max_length=500)),
                ('director', models.CharField(blank=True, help_text='Name of movie director(s).', max_length=200)),
                ('category', models.CharField(choices=[('now_playing', 'Now Playing'), ('popular', 'Popular'), ('top_rated', 'Top Rated'), ('upcoming', 'Upcoming')], db_index=True, default='popular', help_text='Listing category tier on homepage.', max_length=30)),
                ('certificate', models.CharField(choices=[('U', 'U - Unrestricted Public Exhibition'), ('UA', 'UA - Parental Guidance for Children Under 12'), ('A', 'A - Restricted to Adults'), ('S', 'S - Restricted to Special Class')], default='UA', help_text='Censor board age rating certificate.', max_length=5)),
                ('duration', models.PositiveIntegerField(help_text='Total runtime duration in minutes (e.g. 148).')),
                ('release_date', models.DateField(db_index=True, help_text='Official theatrical release date.')),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=8.0, help_text='Aggregate rating score out of 10.0.', max_digits=3)),
                ('popularity', models.IntegerField(db_index=True, default=100, help_text='Calculated popularity score used for sorting catalog items.')),
                ('is_active', models.BooleanField(default=True, help_text='Boolean flag controlling visibility in public listings.')),
                ('cast_members', models.ManyToManyField(blank=True, help_text='Actors and crew featured in the movie.', related_name='movies', to='movies.cast')),
                ('genres', models.ManyToManyField(help_text='Taxonomic genres associated with this movie.', related_name='movies', to='movies.genre')),
                ('language', models.ForeignKey(help_text='Primary audio language of the movie.', on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.language')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-popularity', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('image', models.ImageField(blank=True, help_text='Uploaded poster image file.', null=True, upload_to='movie_gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Remote poster image CDN URL.', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Designates if this poster is the primary showcase banner.')),
                ('movie', models.ForeignKey(help_text='Associated parent movie.', on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Movie Poster',
                'verbose_name_plural': 'Movie Posters',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous visitor session key.', max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(help_text='Target movie viewed.', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_records', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recently Viewed',
                'verbose_name_plural': 'Recently Viewed Movies',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_movi_title_652549_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['category'], name='movies_movi_categor_79c2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-popularity'], name='movies_movi_popular_3c541f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-rating'], name='movies_movi_rating_85da77_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date'], name='movies_movi_release_e8f22e_idx'),
        ),
        migrations.AddConstraint(
            model_name='recentlyviewed',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'movie'), name='unique_user_recently_viewed'),
        ),
        migrations.AddConstraint(
            model_name='recentlyviewed',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'movie'), name='unique_session_recently_viewed'),
        ),
    ]
