# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous visitor session identifier.', max_length=40, null=True)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Page Detail View'), ('SEARCH', 'Search Result Click'), ('BOOKING', 'Completed Booking'), ('FAVORITE', 'Added to Watchlist / Favorites')], db_index=True, default='VIEW', help_text='Type of interaction signal.', max_length=20)),
                ('score_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weighted signal strength for recommendation ranking.', max_digits=4)),
                ('movie', models.ForeignKey(help_text='Target movie item.', on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interaction',
                'verbose_name_plural': 'User Interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='recommendat_user_id_ef4939_idx'), models.Index(fields=['movie', 'interaction_type'], name='recommendat_movie_i_4f515d_idx'), models.Index(fields=['-created_at'], name='recommendat_created_8590c1_idx')],
            },
        ),
    ]
