# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('payment_id', models.CharField(blank=True, db_index=True, help_text='Unique transaction reference identifier returned by payment gateway (e.g. pay_L89Xz2).', max_length=100, null=True, verbose_name='Gateway Transaction ID')),
                ('order_id', models.CharField(blank=True, db_index=True, help_text='Merchant order reference created before payment modal.', max_length=100, null=True, verbose_name='Gateway Order ID')),
                ('signature', models.CharField(blank=True, help_text='HMAC SHA256 signature payload for verification.', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount paid in INR.', max_digits=9)),
                ('currency', models.CharField(default='INR', help_text='Currency code (e.g. INR).', max_length=10)),
                ('provider', models.CharField(choices=[('RAZORPAY', 'Razorpay Gateway'), ('STRIPE', 'Stripe Payments'), ('MOCK', 'Mock / Developer Gateway')], default='RAZORPAY', help_text='Payment processing provider.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Payment Refunded')], db_index=True, default='PENDING', help_text='Current state of payment processing.', max_length=20)),
                ('booking', models.OneToOneField(help_text='Target booking associated with this payment transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'), models.Index(fields=['order_id'], name='payments_pa_order_i_1d1c93_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['-created_at'], name='payments_pa_created_3147e3_idx')],
            },
        ),
    ]
