# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '__first__'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('booking_number', models.CharField(db_index=True, help_text='Unique 12-character booking reference code (e.g. CP-8X92K4).', max_length=20, unique=True, verbose_name='Booking Reference Code')),
                ('total_seats', models.PositiveIntegerField(default=1, help_text='Total number of seats booked in this transaction.')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Subtotal sum of seat prices before fees.', max_digits=9)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=30.0, help_text='Service and convenience fee in INR.', max_digits=7)),
                ('grand_total', models.DecimalField(decimal_places=2, help_text='Final payable amount (total_price + convenience_fee).', max_digits=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired / Timed Out')], db_index=True, default='PENDING', help_text='Transaction confirmation status.', max_length=20)),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR code image for ticket scanning.', null=True, upload_to='qrcodes/')),
                ('pdf_ticket', models.FileField(blank=True, help_text='Generated PDF ticket file for download.', null=True, upload_to='tickets/')),
                ('show', models.ForeignKey(help_text='Showtime screening reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='shows.show')),
                ('user', models.ForeignKey(help_text='Authenticated user who initiated the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('price', models.DecimalField(decimal_places=2, help_text='Specific price charged for this seat.', max_digits=7)),
                ('booking', models.ForeignKey(help_text='Parent booking transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='bookings.booking')),
                ('seat', models.ForeignKey(help_text='Individual seat reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_assignments', to='theaters.seat')),
            ],
            options={
                'verbose_name': 'Booked Seat',
                'verbose_name_plural': 'Booked Seats',
                'ordering': ['seat__row', 'seat__number'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'status'], name='bookings_bo_show_id_d9a7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='bookings_bo_created_7d6386_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='unique_booking_seat_assignment'),
        ),
    ]
