# Generated by Django 5.1.15 on 2026-08-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_bookings_bo_status_eb4fb1_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking'},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_booking_03d631_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_user_id_69a5d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_show_id_d9a7dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_created_7d6386_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_status_eb4fb1_idx',
        ),
    ]
