# Generated by Django 6.0.7 on 2026-07-26 12:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('rating', models.PositiveIntegerField(help_text='Rating score on scale of 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('headline', models.CharField(blank=True, help_text='Short summary headline for review.', max_length=150)),
                ('comment', models.TextField(help_text='Detailed user review text.')),
                ('is_spoiler', models.BooleanField(default=False, help_text='Flag indicating if text contains plot spoilers.')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Total number of helpful votes from other users.')),
                ('movie', models.ForeignKey(help_text='Movie being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(help_text='User submitting the rating or review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movie', '-rating'], name='reviews_rev_movie_i_016c37_idx'), models.Index(fields=['movie', '-created_at'], name='reviews_rev_movie_i_79ac9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_review')],
            },
        ),
    ]
