# Generated by Django 5.1.15 on 2026-08-08 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('reason', models.TextField(help_text='Reason why content is inappropriate or offensive.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('RESOLVED', 'Content Removed / Action Taken'), ('DISMISSED', 'Report Dismissed')], db_index=True, default='PENDING', max_length=20)),
                ('review', models.ForeignKey(help_text='Target review being flagged.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
                ('user', models.ForeignKey(help_text='Reporting user account.', on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Report',
                'verbose_name_plural': 'Review Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reviews_rev_status_90cf38_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'review'), name='unique_user_review_report')],
            },
        ),
    ]
